debug: true
server: "127.0.0.1:8008"
client_secret: "ajwE2zP9WFpOJ41LN779oKrewH5WhbWs"
uuid: "ba9c8fc7-2ffb-4483-8701-23a0379dbdd8"
disable_auto_update: true
disable_nat: true
disable_send_query: false
report_delay: 3
tls: false

